{% set python_min = "3.10" %}
{% set name = "owslib" %}
{% set version = "0.32.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/OWSLib-{{ version }}.tar.gz
  sha256: 339d499849a14b9c27eeebb67fbcfa52c2e7be82251750dab8b5721669cd1f04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - lxml
    - python-dateutil
    - pyyaml
    - requests

test:
  imports:
    - owslib
    - owslib.coverage
    - owslib.feature
    - owslib.swe
    - owslib.swe.observation
    - owslib.swe.sensor
    - owslib.waterml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://geopython.github.io/OWSLib
  license: BSD-3-Clause
  license_file: LICENSE
  summary: OGC Web Service utility library

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - pelson
    - ocefpaf
