{% set version = "0.31.0" %}

package:
  name: owslib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/O/OWSLib/OWSLib-{{ version }}.tar.gz
  sha256: 2ed6540087445cc57d905138a590b6ae58624ec7661b5c1682ed4e3303bcd150

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - dataclasses
    - python >=3.8
    - lxml
    - python-dateutil >=1.5
    - pytz
    - pyyaml
    - requests >=1.0

test:
  imports:
    - owslib
    - owslib.coverage
    - owslib.feature
    - owslib.swe
    - owslib.swe.observation
    - owslib.swe.sensor
    - owslib.waterml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://geopython.github.io/OWSLib
  license: BSD-3-Clause
  license_file: LICENSE
  summary: OGC Web Service utility library

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - pelson
    - ocefpaf
